master: integrating feature_ww3env to the master VLab #51784 > Modification to run w3_setenv without interaction
Former-commit-id: 46a1ae1bf349409c2a8e490ff9a38ef87f620161

diff --git a/model/bin/ad3 b/model/bin/ad3
--- a/model/bin/ad3
+++ b/model/bin/ad3
@@ -320,13 +320,28 @@ then
 
   error='0'
 
-  if $path_b/comp $name > comp.out.$name 2> comp.err.$name
+  $path_b/comp $name > comp.out.$name 2> comp.err.$name
+  OK="$?"
+
+
+# 3.b Error escape location  - - - - - - - - - - - - - - - - - - - - - - - - -
+  if [ "$OK" != '0' ]
   then
-    rm -f comp.err.$name
-    rm -f comp.out.$name
+    echo '      *** compile error ***'
+    echo '          error in comp'
+    echo '--- comp output -------------------------------------------------'
+    cat comp.out.$name
+    echo '--- comp error output -------------------------------------------'
+    cat comp.err.$name
+    echo '-----------------------------------------------------------------'
+    error='6'
+    rm -f comp.stat.$name
+  fi
+  rm -f comp.out.$name
+  rm -f comp.err.$name
 
-# 3.b Check comp.stat  - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
+# 3.c Check comp.stat  - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     if [ -f comp.stat.$name ]
     then
       nr_err=`grep ERROR comp.stat.$name | awk '{ print $2 }'`
@@ -345,13 +360,13 @@ then
       fi
     else
       echo '      *** compile error ***'
-      echo '          file comp.stat not found'
+      echo "          file comp.stat.$name not found"
       error='5'
       nr_err='1'
       rm -f $name.o
     fi
 
-# 3.c process object file  - - - - - - - - - - - - - - - - - - - - - - - - - -
+# 3.d process object file  - - - - - - - - - - - - - - - - - - - - - - - - - -
 
     if [ "$nr_err" != '0' ] && [ ! -f $name.o ] && [ "$error" = '0' ]
     then
@@ -379,19 +394,6 @@ then
 # Note: the need for moving the .mod file and therefore the printing of the
 #       $mod depend on the compiler behavior.
 
-# 3.d Error escape location  - - - - - - - - - - - - - - - - - - - - - - - - -
-
-  else
-    echo '      *** compile error ***'
-    echo '          error in comp'
-    echo '--- comp output -------------------------------------------------'
-    cat comp.out.$name
-    echo '--- comp error output -------------------------------------------'
-    cat comp.err.$name
-    echo '-----------------------------------------------------------------'
-    rm -f comp.*.$name
-    error='6'
-  fi
 
 # 3.e process output files - - - - - - - - - - - - - - - - - - - - - - - - - -
 
diff --git a/model/bin/sort_switch b/model/bin/sort_switch
--- a/model/bin/sort_switch
+++ b/model/bin/sort_switch
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -e
 # --------------------------------------------------------------------------- #
 # sort_switch: Script to unify the way the switches are ordered in the switch #
 #              file, while checking and correcting for missing switches.      #
@@ -303,10 +303,10 @@ EOF
    
     done
 
-#   if [ "$verbose" ]
-#   then
-#     echo "    $key $i_fnd $found [$OK]"
-#   fi
+   if [ "$verbose" ]
+   then
+     echo "    $key $i_fnd $found [$OK]"
+   fi
 
 # 3.d Too many switches found (error)
 
@@ -361,7 +361,7 @@ EOF
 
 # 3.e.4 unknown default
 
-     *  ) echo 'ooops' ; exit 99 ;;
+     *  ) echo "[error in sort_switch] unknown type $TY" ; exit 99 ;;
     esac
 
     if [ "$verbose" ]
diff --git a/model/bin/w3_setenv b/model/bin/w3_setenv
--- a/model/bin/w3_setenv
+++ b/model/bin/w3_setenv
@@ -2,7 +2,8 @@
 # --------------------------------------------------------------------------- #
 # w3_setenv : Set wwatch3 env and verify the consistency of the paths used    #
 #                                                                             #
-# use     : w3_setenv                                                         #
+# use     : w3_setenv [options]                                               #
+#              -q: "quiet", do not ask for updating the WWATCH3 path          #
 #                                                                             #
 # programs used :                                                             #
 #       w3_clean                                                              #
@@ -37,6 +38,63 @@
 #       No unauthorized use without permission.                               #
 #                                                                             #
 # --------------------------------------------------------------------------- #
+
+# --------------------------------------------------------------------------- #
+# 0. Process command line arguments                                           #
+# --------------------------------------------------------------------------- #
+
+myname="`basename $0`"  #name of script
+
+# 0.a Error message function
+  errmsg ()
+  {
+    echo "" 2>&1
+    while [ $# != 0 ]
+    do
+      echo "$myname: ERROR: $1" 2>&1
+      shift
+    done
+    echo "" 2>&1
+  }
+
+# 0.b Usage function
+  optstr="q"  #option string for getopt function
+  usage ()
+  {
+cat 2>&1 << EOF
+
+Usage: $myname [options]
+Required: none
+Options:
+  -q : "quiet", do not ask for updating the WWATCH3 path
+
+EOF
+  }
+
+# 0.c Setup array of command-line arguments
+  args=`getopt $optstr $*`
+  if [ $? != 0 ]
+  then
+    usage
+    exit 1
+  fi
+  set -- $args
+
+# 0.d Process command-line options
+  while :
+  do
+    case "$1" in
+    -q) quiet=1 ;;
+    --) break ;;
+    esac
+    shift
+  done
+  shift #remove the trailing --
+  if [ $help ]
+  then
+    usage
+    exit 1
+  fi
 
 
 # --------------------------------------------------------------------------- #
@@ -93,43 +151,46 @@
 
   path_mod="$(cd $(dirname $path_bin) 1>/dev/null 2>&1 && pwd)"
 
-  if [ -z "$(echo $path_mod | grep $main_dir)" ]
+  if [ ! $quiet ] 
   then
-    echo ""
-    echo "[WARNING] WWATCH3_DIR does not match current path"
-    echo "          CURRENT DIR = $path_mod"
-    echo "          WWATCH3_DIR = $main_dir"
-    echo ""
-    echo "Update WWATCH3_DIR [u] or keep [k] or exit [e] ?"
-    read OK
-    case $OK in
-      'u'|'U') do_set='y' ;;
-      'k'|'K') do_set='n' ;;
-      'e'|'E') exit       ;;
-    esac
-    if [ "$do_set" = 'y' ]
+    if [ -z "$(echo $path_mod | grep $main_dir)" ]
     then
-      $path_bin/w3_setup -t "$path_mod/tmp" $path_mod
+      echo ""
+      echo "[WARNING] WWATCH3_DIR does not match current path"
+      echo "          CURRENT DIR = $path_mod"
+      echo "          WWATCH3_DIR = $main_dir"
+      echo ""
+      echo "Update WWATCH3_DIR [u] or keep [k] or exit [e] ?"
+      read OK
+      case $OK in
+        'u'|'U') do_set='y' ;;
+        'k'|'K') do_set='n' ;;
+        'e'|'E') exit       ;;
+      esac
+      if [ "$do_set" = 'y' ]
+      then
+        $path_bin/w3_setup -t "$path_mod/tmp" $path_mod
+      fi
     fi
-  fi
 
-  if [ -z "$(echo $temp_dir | grep $main_dir)" ]
-  then
-    echo ""
-    echo "[WARNING] WWATCH3_TMP does not match WWATCH3_DIR"
-    echo "          WWATCH3_TMP = $temp_dir"
-    echo "          WWATCH3_DIR = $main_dir"
-    echo ""
-    echo "Update WWATCH3_DIR [u] or keep [k] or exit [e] ?"
-    read OK
-    case $OK in
-      'y'|'Y') do_set='y' ;;
-      'k'|'K') do_set='n' ;;
-      'e'|'E') exit       ;;
-    esac
-    if [ "$do_set" = 'y' ]
+    if [ -z "$(echo $temp_dir | grep $main_dir)" ]
     then
-      $path_bin/w3_setup -t "$path_mod/tmp" $path_mod
+      echo ""
+      echo "[WARNING] WWATCH3_TMP does not match WWATCH3_DIR"
+      echo "          WWATCH3_TMP = $temp_dir"
+      echo "          WWATCH3_DIR = $main_dir"
+      echo ""
+      echo "Update WWATCH3_DIR [u] or keep [k] or exit [e] ?"
+      read OK
+      case $OK in
+        'y'|'Y') do_set='y' ;;
+        'k'|'K') do_set='n' ;;
+        'e'|'E') exit       ;;
+      esac
+      if [ "$do_set" = 'y' ]
+      then
+        $path_bin/w3_setup -t "$path_mod/tmp" $path_mod
+      fi
     fi
   fi
 
