Trunk : Reintegrating branch cpp  into Trunk. This reintegration adds the  cpp preprocessing capability to WAVEWATCH III. At the moment the cpp macros  have only been enabled to check allocation / deallocation status. The branch  was also used to clean up some bugs in w3_source and allow NEXTLN to have  leading blanks.
Former-commit-id: ed5035e7305da1d01049a826e4efcbb3c00e2b16

diff --git a/model/bin/ad3 b/model/bin/ad3
--- a/model/bin/ad3
+++ b/model/bin/ad3
@@ -87,7 +87,7 @@
     icmp='0'
   fi
 
-# 1.b Internal variables - - - - - - - - - - - - - - - - - - - - - - - - - - - 
+# 1.b Internal variables - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
   ww3_env="${HOME}/.wwatch3.env"                           # setup file
 # The following line must not be removed: it is a switch for local install
@@ -122,7 +122,7 @@
     exit 2
   fi
 
-# 1.d Set up paths etc.  - - - - - - - - - - - - - - - - - - - - - - - - - - - 
+# 1.d Set up paths etc.  - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
   path_b="$main_dir/bin"
   path_w="$temp_dir"
@@ -158,7 +158,34 @@
     idstr='[no w3adc]'
   fi
 
-# 1.f Output - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
+# 1.f Set appropriate Fortran file suffix  - - - - - - - - - - - - - - - - - -
+
+  suffixes="ftn f F f90 F90 c"
+  fexti=none
+  for s in $suffixes
+  do
+    if [ -f $path_i/$name.$s ]
+    then
+      fexti=$s
+      break
+    fi
+  done
+  if [ "$fexti" = 'none' ]
+  then
+    echo '      *** ad3 error ***'
+    echo "          Source file $path_i/$name.* not found"
+    echo "          Source file suffixes checked: $suffixes"
+    exit 2
+  fi
+  if [ "$fexti" = 'ftn' ]
+  then
+    fexto=F90
+  else
+    fexto=$fexti
+  fi
+  fext=$fexto
+
+# 1.g Output - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
   echo "ad3 : processing $name $idstr"
 
@@ -176,10 +203,10 @@
     echo ' '
   fi
 
-# 1.g Final preparations - - - - - - - - - - - - - - - - - - - - - - - - - - - 
+# 1.h Final preparations - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
   cd $path_w
-  rm -f $name.f $name.f90
+  rm -f $name.$fext
   rm -f $name.l
   ln -s $main_dir/bin/w3list . 2> /dev/null
 
@@ -192,7 +219,7 @@
   then
 
     echo "0 $compress"                             > w3adc.inp
-    echo "'$path_i/$name.ftn' '$name.f90'"        >> w3adc.inp
+    echo "'$path_i/$name.ftn' '$name.$fext'"      >> w3adc.inp
     echo "'$sw_str'"                              >> w3adc.inp
 
 # 2.b Add NCEP/NCO docmentation  - - - - - - - - - - - - - - - - - - - - - - -
@@ -210,7 +237,7 @@
 
     $path_b/w3adc < w3adc.inp > w3adc.out 2> w3adc.err
 
-# 2.c Test the output of w3adc - - - - - - - - - - - - - - - - - - - - - - - - 
+# 2.c Test the output of w3adc - - - - - - - - - - - - - - - - - - - - - - - -
 
     ad3_tst="`grep ERROR w3adc.out`"
     if [ -n "$ad3_tst" ]
@@ -219,17 +246,17 @@
       echo "     $ad3_tst" ; exit 4
     fi
 
-    if [ ! -f $name.f90 ]
+    if [ ! -f $name.$fext ]
     then
       echo '      *** w3adc error ***'
-      echo "          file $name.f90 not found (1)."
+      echo "          file $name.$fext not found (1)."
       cat w3adc.out ; cat w3adc.err  ; exit 4
     fi
 
-    if [ "`wc -l $name.f90 | awk '{ print $1}'`" -lt '2'  ]
+    if [ "`wc -l $name.$fext | awk '{ print $1}'`" -lt '2'  ]
     then
       echo '      *** w3adc error ***'
-      echo "          file $name.f90 not found (2)."
+      echo "          file $name.$fext not found (2)."
       cat w3adc.out ; cat w3adc.err  ; exit 4
     fi
 
@@ -238,57 +265,44 @@
       cat w3adc.out
     fi
 
-# 2.d Clean up - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
+# 2.d Clean up - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
     rm -f w3adc.*
 
 # 2.e Add switches in w3initmd - - - - - - - - - - - - - - - - - - - - - -
 
     if [ "$name" = "w3initmd" ]
-    then 
+    then
       sw_1=''
-      cp $path_w/w3initmd.f90  $path_w/w3initmd.ft1
-      for line in 1 2 3 
-        do 
+      cp $path_w/w3initmd.$fext  $path_w/w3initmd.ft1
+      for line in 1 2 3
+        do
           sw_1=`echo $sw_str  | fold -w100 | sed -n "${line}p"`
           sw_old="PUT_SW$line"
           # echo $line  $sw_1 $sw_old
           sed -e "s/$sw_old/$sw_1/"  $path_w/w3initmd.ft1 > $path_w/w3initmd.ft2
-          mv  $path_w/w3initmd.ft2 $path_w/w3initmd.ft1 
-        done 
-      mv $path_w/w3initmd.ft1 $path_w/w3initmd.f90
-      echo "'$path_w/$name.fts' '$name.f90'"        >> w3adc.inp
+          mv  $path_w/w3initmd.ft2 $path_w/w3initmd.ft1
+        done
+      mv $path_w/w3initmd.ft1 $path_w/w3initmd.$fext
+      echo "'$path_w/$name.fts' '$name.$fext'"        >> w3adc.inp
     fi
 
   else
 
-# 2.f No w3adc, just copy file - - - - - - - - - - - - - - - - - - - - - - - - 
+# 2.f No w3adc, just copy file - - - - - - - - - - - - - - - - - - - - - - - -
 
-    if [ -f $path_i/$name.f90 ]
-    then
-      cp $path_i/$name.f90 .
-    else
-      if [ -f $path_i/$name.f ]
-      then
-        cp $path_i/$name.f .
-      fi
-    fi
-
-    if [ -f $path_i/$name.c ]
-    then
-      cp $path_i/$name.c .
-    fi
+    cp $path_i/$name.$fext .
 
   fi
 
-  if [ ! -f $name.f ]  && [ ! -f $name.f90 ]&& [ ! -f $name.c ]
+  if [ ! -f $name.$fext ]
   then
     echo '      *** adc error ***'
-    echo "          file $name.f|f90|c not found."
+    echo "          file $name.$fext not found."
     exit 5
   fi
 
-# 2.g Stop if requested  - - - - - - - - - - - - - - - - - - - - - - - - - - - 
+# 2.g Stop if requested  - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
   if [ "$icmp" != '0' ]
   then
@@ -303,6 +317,10 @@
 # 3. Compile source code f / f90                                              #
 # --------------------------------------------------------------------------- #
 
+export fext    # for use by comp
+export path_m  # for use by comp
+export path_i  # for use by comp
+
 if [ ! -f $name.c ]
 then
 
@@ -310,14 +328,12 @@ then
 
   error='0'
 
-  export path_m 
-
   if $path_b/comp $name > comp.out 2> comp.err
   then
     rm -f comp.err
     rm -f comp.out
 
-# 3.b Check comp.stat  - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
+# 3.b Check comp.stat  - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
     if [ -f comp.stat ]
     then
@@ -343,9 +359,9 @@ then
       rm -f $name.o
     fi
 
-# 3.c process object file  - - - - - - - - - - - - - - - - - - - - - - - - - - 
+# 3.c process object file  - - - - - - - - - - - - - - - - - - - - - - - - - -
 
-    if [ "$nr_err" = '0' ] && [ ! -f $name.o ] && [ "$error" = '0' ]
+    if [ "$nr_err" != '0' ] && [ ! -f $name.o ] && [ "$error" = '0' ]
     then
       echo '      *** compile error ***'
       echo "          file $name.o not found"
@@ -368,10 +384,10 @@ then
       fi
     fi
 
-# Note: the need for moving the .mod file and therefore the printing of the 
+# Note: the need for moving the .mod file and therefore the printing of the
 #       $mod depend on the compiler behavior.
 
-# 3.d Error escape location  - - - - - - - - - - - - - - - - - - - - - - - - - 
+# 3.d Error escape location  - - - - - - - - - - - - - - - - - - - - - - - - -
 
   else
     echo '      *** compile error ***'
@@ -384,15 +400,15 @@ then
     rm -f comp.*
     error='6'
   fi
- 
-# 3.e process output files - - - - - - - - - - - - - - - - - - - - - - - - - - 
+
+# 3.e process output files - - - - - - - - - - - - - - - - - - - - - - - - - -
 
   rm -f $name.o
   rm -f w3list
 
   if [ "$source" != 'yes' ]
   then
-    rm -f $name.f $name.f90
+    rm -f $name.f $name.$fext
   fi
   if [ "$list" != 'yes' ] && [ "$error" = '0' ]
   then
