add options for METIS and SCOTCH to GNU build

diff --git a/model/bin/link.tmpl b/model/bin/link.tmpl
--- a/model/bin/link.tmpl
+++ b/model/bin/link.tmpl
@@ -117,12 +117,12 @@
     libs="$libs `$NETCDF_CONFIG --flibs` `$NETCDF_CONFIG --libs`"
   fi
 
-  # parmetis library 
+  # scotch library 
   if [ "$prog" = 'ww3_shel' ] || [ "$prog" = 'ww3_multi' ] || [ "$prog" = 'ww3_sbs1' ] ; then
-    if [ "$pdlib_mod" = 'yes' ] ; then
+    if [ "$scotch_mod" = 'yes' ] ; then
       if [ -z "$(env | grep SCOTCH_PATH)" ] ; then
         echo ''
-        echo "[ERROR] METIS_PATH is not defined"
+        echo "[ERROR] SCOTCH_PATH is not defined"
         exit 1
       fi
       echo "link with scotch" 
@@ -132,17 +132,17 @@
 
 
   # parmetis library
-#  if [ "$prog" = 'ww3_shel' ] || [ "$prog" = 'ww3_multi' ] || [ "$prog" = 'ww3_sbs1' ] ; then
-#    if [ "$pdlib_mod" = 'yes' ] ; then
-#      if [ -z "$(env | grep METIS_PATH)" ] ; then
-#        echo ''
-#        echo "[ERROR] METIS_PATH is not defined"
-#        exit 1
-#      fi
-#      echo "link with parmetis"
-#      libs="$libs $METIS_PATH/lib/libparmetis.a $METIS_PATH/lib/libmetis.a"
-#    fi
-#  fi
+  if [ "$prog" = 'ww3_shel' ] || [ "$prog" = 'ww3_multi' ] || [ "$prog" = 'ww3_sbs1' ] ; then
+    if [ "$metis_mod" = 'yes' ] ; then
+      if [ -z "$(env | grep METIS_PATH)" ] ; then
+        echo ''
+        echo "[ERROR] METIS_PATH is not defined"
+        exit 1
+      fi
+      echo "link with parmetis"
+      libs="$libs $METIS_PATH/lib/libparmetis.a $METIS_PATH/lib/libmetis.a"
+    fi
+  fi
 
   # OMP support
   if [ "$omp_mod" = 'yes' ] ; then
