ww3/trunk/model subdirectory
  * Merging ww3/branches/curv/model r5156:6931 into trunk, no conflicts




Former-commit-id: 0d5c0050dca520c8ead5781f3ab7eeabaaf860d1

diff --git a/model/bin/w3_clean b/model/bin/w3_clean
--- a/model/bin/w3_clean
+++ b/model/bin/w3_clean
@@ -3,7 +3,9 @@
 # w3_clean : Clean-up the work, test and scratch directories by removing the  #
 #            files generated by WAVEWATCH III and its compilation system.     #
 #                                                                             #
-# use  : w3_clean                                                             #
+# use  : w3_clean [-c]                                                        #
+#           -c: "clobber", also clean-up model directories.                   #
+#                                                                             #
 #                                                      Hendrik L. Tolman      #
 #                                                      May 2009               #
 #                                                                             #
@@ -12,6 +14,60 @@
 #       reserved.  WAVEWATCH III is a trademark of the NWS.                   #
 #       No unauthorized use without permission.                               #
 #                                                                             #
+# --------------------------------------------------------------------------- #
+# 0. Process command line arguments                                           #
+# --------------------------------------------------------------------------- #
+myname="`basename $0`"  #name of script
+
+# 0.a Error message function
+  errmsg ()
+  {
+    echo "" 2>&1
+    while [ $# != 0 ]
+    do
+      echo "$myname: ERROR: $1" 2>&1
+      shift
+    done
+    echo "" 2>&1
+  }
+
+# 0.b Usage function
+  optstr="c"  #option string for getopt function
+  usage ()
+  {
+    echo "" 2>&1
+    echo "Usage: $myname [-c]" 2>&1
+    echo "Required: none" 2>&1
+    echo "Options:" 2>&1
+    echo "  -c : also clean-up model directories" 2>&1
+    echo "" 2>&1
+  }
+
+# 0.c Setup array of command-line arguments
+  args=`getopt $optstr $*`
+  if [ $? != 0 ]
+  then
+    usage
+    exit 1
+  fi
+  set -- $args
+
+# 0.d Process command-line options
+  while :
+  do
+    case "$1" in
+    -c) clobber=1 ;;
+    --) break ;;
+    esac
+    shift
+  done
+  shift #remove the trailing --
+  if [ $help ]
+  then
+    usage
+    exit 1
+  fi
+
 # --------------------------------------------------------------------------- #
 # 1. Preparations                                                             #
 # --------------------------------------------------------------------------- #
@@ -29,7 +85,7 @@
     set `grep WWATCH3_TMP $ww3_env` ; shift
     temp_dir="$*"
   else
-    echo "*** Set-up file $ww3_env not found ***"
+    errmsg "*** Set-up file $ww3_env not found ***"
     exit 2
   fi
 
@@ -37,39 +93,44 @@
 # 2. Scratch directory                                                        #
 # --------------------------------------------------------------------------- #
 
-  cd $temp_dir
-
-  rm -f core
-  rm -fr coredir.*
-  rm -f *.f
-  rm -f *.f90
-  rm -f *.l
-  rm -f *.o
-  rm -f *.inp
-  rm -f *.out
-  rm -f *.err
-  rm -f *.ps
-  rm -f *.eps
-  rm -f *.ww3
-  rm -f *.mww3
-  rm -f mod_def.*
-  rm -f out_pnt.*
-  rm -f out_grd.*
-  rm -f restart*.*
-  rm -f partition*.*
-  rm -f buoy_log*.*
-  rm -f log.*
-  rm -f test.*
-  rm -f test???.*
-  rm -f w3list
-  rm -f ww3.????????.*
-  rm -f xnl4v5*
-  rm -f quad*
-  rm -f prf.*.mww3
-  rm -f plot.grads*
-  rm -f buoy.data
-  rm -f fort.*
-  rm -f times.*
+  if [ -d $temp_dir ]
+  then
+    echo "   Clean up $temp_dir"
+    cd $temp_dir
+    rm -f core
+    rm -fr coredir.*
+    rm -f *.f
+    rm -f *.f90
+    rm -f *.l
+    rm -f *.o
+    rm -f *.inp
+    rm -f *.out
+    rm -f *.err
+    rm -f *.ps
+    rm -f *.eps
+    rm -f *.ww3
+    rm -f *.mww3
+    rm -f mod_def.*
+    rm -f out_pnt.*
+    rm -f out_grd.*
+    rm -f restart*.*
+    rm -f partition*.*
+    rm -f buoy_log*.*
+    rm -f log.*
+    rm -f test.*
+    rm -f test???.*
+    rm -f w3list
+    rm -f ww3.????????.*
+    rm -f xnl4v5*
+    rm -f quad*
+    rm -f prf.*.mww3
+    rm -f plot.grads*
+    rm -f buoy.data
+    rm -f fort.*
+    rm -f times.*
+  else
+    echo "   Directory does not exist: $temp_dir"
+  fi
 
 # --------------------------------------------------------------------------- #
 # 3. Work and test directories                                                #
@@ -77,54 +138,106 @@
 
   for dir in $main_dir/work $main_dir/test
   do
-    cd $dir
-    rm -f core
-    rm -fr coredir.*
-    rm -f mod_def.ww3
-    rm -f restart*.ww3
-    rm -f nest*.ww3
-    rm -f partition*.ww3
-    rm -f buoy_log*.*
-    rm -f out_pnt.*
-    rm -f out_grd.*
-    rm -f level.ww3
-    rm -f current.ww3
-    rm -f wind.ww3
-    rm -f ice.ww3
-    rm -f track_o.ww3
-    rm -f track.ww3
-    rm -f test.ww3
-    rm -f test???.ww3
-    rm -f test.mod*
-    rm -f test???.mod*
-    rm -f log.*
-    rm -f tab??.*
-    rm -f *.tab
-    rm -f mask.ww3
-    rm -f mapsta.ww3
-    rm -f data?.ww3
-    rm -f *.mww3
-    rm -f *.out
-    rm -f *.ps
-    rm -f *.eps
-    rm -f gmeta
-    rm -f ww3.????????.*
-    rm -f ww3_????.f
-    rm -f ww3_????.tar
-    rm -f gx_????.f
-    rm -f gx_????.tar
-    rm -f plot.grads*
-    rm -f fort.*
-    rm -f xnl4v5*
-    rm -f quad*
-    rm -f grads.*
-    rm -f prf.*.mww3
-    rm -f buoy.data
-    rm -f buoy.all
-    rm -f *.ctl
-    rm -f ww3.*
-    rm -f *.gs_tmpl
-    rm -f times.*
+    if [ -d $dir ]
+    then
+      echo "   Clean up $dir"
+      cd $dir
+      rm -f core
+      rm -fr coredir.*
+      rm -f mod_def.ww3
+      rm -f restart*.ww3
+      rm -f nest*.ww3
+      rm -f partition*.ww3
+      rm -f buoy_log*.*
+      rm -f out_pnt.*
+      rm -f out_grd.*
+      rm -f level.ww3
+      rm -f current.ww3
+      rm -f wind.ww3
+      rm -f ice.ww3
+      rm -f track_o.ww3
+      rm -f track.ww3
+      rm -f test.ww3
+      rm -f test???.ww3
+      rm -f test.mod*
+      rm -f test???.mod*
+      rm -f log.*
+      rm -f tab??.*
+      rm -f *.tab
+      rm -f mask.ww3
+      rm -f mapsta.ww3
+      rm -f data?.ww3
+      rm -f *.mww3
+      rm -f *.out
+      rm -f *.ps
+      rm -f *.eps
+      rm -f gmeta
+      rm -f ww3.????????.*
+      rm -f ww3_????.f
+      rm -f ww3_????.tar
+      rm -f gx_????.f
+      rm -f gx_????.tar
+      rm -f plot.grads*
+      rm -f fort.*
+      rm -f xnl4v5*
+      rm -f quad*
+      rm -f grads.*
+      rm -f prf.*.mww3
+      rm -f buoy.data
+      rm -f buoy.all
+      rm -f *.ctl
+      rm -f ww3.*
+      rm -f *.gs_tmpl
+      rm -f times.*
+    else
+      echo "   Directory does not exist: $dir"
+    fi
   done
+
+# --------------------------------------------------------------------------- #
+# 4. Model directories                                                        #
+# --------------------------------------------------------------------------- #
+
+  if [ $clobber ]
+  then
+    if [ -d $main_dir ]
+    then
+      if [ -d $main_dir/bin ]
+      then
+        echo "   Clean up $main_dir/bin"
+        cd $main_dir/bin
+        rm -f w3adc w3list w3prnt w3split comp link switch switch.old
+      fi
+      if [ -d $main_dir/aux ]
+      then
+        echo "   Clean up $main_dir/aux"
+        cd $main_dir/aux
+        rm -f makefile
+      fi
+      if [ -d $main_dir/ftn ]
+      then
+        echo "   Clean up $main_dir/ftn"
+        cd $main_dir/ftn
+        rm -f makefile
+      fi
+      if [ -d $main_dir/exe ]
+      then
+        echo "   Remove $main_dir/exe"
+        rm -fr $main_dir/exe
+      fi
+      if [ -d $main_dir/obj ]
+      then
+        echo "   Remove $main_dir/obj"
+        rm -fr $main_dir/obj
+      fi
+      if [ -d $main_dir/mod ]
+      then
+        echo "   Remove $main_dir/mod"
+        rm -fr $main_dir/mod
+      fi
+    else
+      echo "   Directory does not exist: $main_dir"
+    fi
+  fi
 
 # End of w3_clean ----------------------------------------------------------- #
